Updating script so they can also run from outside the VM

diff --git a/bin/behat b/bin/behat
--- a/bin/behat
+++ b/bin/behat
@@ -1,2 +1,19 @@
 #!/bin/bash
-/vagrant/src/vendor/bin/behat
+scrDir="`dirname \"$0\"`"             # relative
+scrDir="`( cd \"$scrDir\" && pwd )`"  # absolutized and normalized
+if [ -z "$scrDir" ] ; then
+  # error; for some reason, the path is not accessible
+  # to the script (e.g. permissions re-evaled after suid)
+  exit 1  # fail
+fi
+
+machineName=$(cat "$scrDir/../hostname")
+hostName="`( hostname -f )`"
+if [ "$hostName" = "$machineName" ]; then
+	echo "running from inside the VM"
+
+	cd /vagrant/src
+	/vagrant/src/vendor/bin/behat
+else
+	vagrant ssh -c '/vagrant/bin/behat'
+fi
diff --git a/bin/build b/bin/build
--- a/bin/build
+++ b/bin/build
@@ -1,3 +1,19 @@
 #!/bin/bash
-cd /vagrant
-/usr/local/bin/gulp
+scrDir="`dirname \"$0\"`"             # relative
+scrDir="`( cd \"$scrDir\" && pwd )`"  # absolutized and normalized
+if [ -z "$scrDir" ] ; then
+  # error; for some reason, the path is not accessible
+  # to the script (e.g. permissions re-evaled after suid)
+  exit 1  # fail
+fi
+
+machineName=$(cat "$scrDir/../hostname")
+hostName="`( hostname -f )`"
+if [ "$hostName" = "$machineName" ]; then
+	echo "running from inside the VM"
+
+	cd /vagrant/src
+	/usr/local/bin/gulp
+else
+	vagrant ssh -c '/vagrant/bin/build'
+fi
diff --git a/bin/dumpdb b/bin/dumpdb
--- a/bin/dumpdb
+++ b/bin/dumpdb
@@ -1,8 +1,24 @@
 #!/bin/bash
-date=$(date +'%Y-%m-%d %H:%M:%S')
-read Y M D h m s <<< ${date//[-: ]/ }
+scrDir="`dirname \"$0\"`"             # relative
+scrDir="`( cd \"$scrDir\" && pwd )`"  # absolutized and normalized
+if [ -z "$scrDir" ] ; then
+  # error; for some reason, the path is not accessible
+  # to the script (e.g. permissions re-evaled after suid)
+  exit 1  # fail
+fi
 
-if [ ! -f "/vagrant/dbdumps/" ]; then mkdir /vagrant/dbdumps/; fi;
-mkdir /vagrant/dbdumps/
-/usr/bin/mysqldump -uroot -plocalpassword localdatabase > "/vagrant/dbdumps/$Y$M$D ${h}h$m db_dump.sql"
+machineName=$(cat "$scrDir/../hostname")
+hostName="`( hostname -f )`"
+if [ "$hostName" = "$machineName" ]; then
+	echo "running from inside the VM"
+
+	date=$(date +'%Y-%m-%d %H:%M:%S')
+	read Y M D h m s <<< ${date//[-: ]/ }
+
+	if [ ! -f "/vagrant/dbdumps/" ]; then mkdir /vagrant/dbdumps/; fi;
+	mkdir /vagrant/dbdumps/
+	/usr/bin/mysqldump -uroot -plocalpassword localdatabase > "/vagrant/dbdumps/$Y$M$D ${h}h$m db_dump.sql"
+else
+	vagrant ssh -c '/vagrant/bin/dumpdb'
+fi
 
diff --git a/bin/seed b/bin/seed
--- a/bin/seed
+++ b/bin/seed
@@ -1,4 +1,20 @@
 #!/bin/bash
+scrDir="`dirname \"$0\"`"             # relative
+scrDir="`( cd \"$scrDir\" && pwd )`"  # absolutized and normalized
+if [ -z "$scrDir" ] ; then
+  # error; for some reason, the path is not accessible
+  # to the script (e.g. permissions re-evaled after suid)
+  exit 1  # fail
+fi
 
-/usr/bin/php /vagrant/src/artisan migrate --package=rydurham/sentinel
-/usr/bin/php /vagrant/src/artisan db:seed --class="SentinelDatabaseSeeder"
+machineName=$(cat "$scrDir/../hostname")
+hostName="`( hostname -f )`"
+if [ "$hostName" = "$machineName" ]; then
+	echo "running from inside the VM"
+
+	/usr/bin/php /vagrant/src/artisan migrate --package=rydurham/sentinel
+	/usr/bin/php /vagrant/src/artisan db:seed --class="SentinelDatabaseSeeder"
+else
+	vagrant ssh -c '/vagrant/bin/seed'
+fi
+
